version: "2"

services:
  tegola:
    image: gospatial/tegola:v0.10.2
    ports: ["8080:8080"]
    links: ["db"]
    environment:
      PGHOST: db
    command: 
      - serve
      - --config 
      - /src/config.toml
    volumes:
      - ".:/src"
  db:
    image: kartoza/postgis:9.6-2.4
    ports: ["5432:5432"]
    environment:
      POSTGRES_DBNAME: osm
      POSTGRES_USER: osm
      POSTGRES_PASS: osm
      ALLOW_IP_RANGE: 172.17.0.0/8
    volumes:
      - ".:/src"
      - "/var/lib/postgresql"

  web:
    image: node:alpine
    ports: ["80:8000"]
    environment:
      PUBLIC_PATH: "/var/www"
    working_dir: "/srv/proxy"
    volumes:
      - "./demo:/var/www"
      - "./proxy:/srv/proxy"
    command: ["/srv/proxy/server.sh"]

  maputnik:
    image: maputnik/editor:latest
    ports: ["8888:8888"]

