version: "2"

services:
  tegola:
    image: debian:stable-slim
    links: ["db"]
    environment:
      PGHOST: db
    working_dir: /src
    entrypoint: /bin/sh -c "/src/generate_config.sh && /src/tegola serve --config /src/config.toml"
    volumes:
      - ".:/src"

  db:
    image: postgis/postgis:13-3.0
    environment:
      POSTGRES_DBNAME: osm
      POSTGRES_USER: osm
      POSTGRES_PASSWORD: osm
    volumes:
      - ".:/src"
      - "/var/lib/postgresql"

  web:
    image: node:alpine
    ports: ["80:8000"]
    links: ["tegola"]
    environment:
      PUBLIC_PATH: "/var/www"
      TILES_URL: "http://tegola:8082/all/{z}/{x}/{y}.pbf"
    working_dir: "/srv/proxy"
    volumes:
      - "./demo:/var/www"
      - "./proxy:/srv/proxy"
    command: ["/srv/proxy/server.sh"]

  maputnik:
    image: maputnik/editor:latest
    ports: ["8888:8888"]

