version: "2"

services:
  tegola:
    image: debian:stable-slim
    network_mode: service:net
    working_dir: /src
    entrypoint: /bin/sh -c "/src/generate_config.sh && /src/tegola serve --config /src/config.toml"
    volumes:
      - ".:/src" # for tegola binary and config.toml

  db:
    image: postgis/postgis:13-3.0
    network_mode: service:net
    environment:
      POSTGRES_DBNAME: osm
      POSTGRES_USER: osm
      POSTGRES_PASSWORD: osm
    volumes:
      - ".:/src:ro"
      - "/var/lib/postgresql"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3-amd64
    network_mode: service:net
    environment:
      discovery.type: single-node
      http.port: 9500
    volumes:
      - "/usr/share/elasticsearch/data"

  web:
    image: nginx:stable
    network_mode: service:net
    volumes:
      - ".:/src:ro"
      - "./nginx.conf:/etc/nginx/conf.d/openmap.conf:ro"

  maputnik:
    image: maputnik/editor:latest
    network_mode: service:net

  net:
    image: debian:stable-slim
    entrypoint: ["tail", "-f", "/dev/null"]
    ports:
      - "5432:5432" # postgresql
      - "8080:8080" # web -- nginx
      - "8888:8888" # maputnik
      - "9500:9500" # elastic
