version: "2"

services:
  tegola:
    image: xor22h/tegola:v0.10.2
    links: ["db"]
    environment:
      PGHOST: db
    working_dir: /src
    entrypoint: /bin/sh -c "/src/generate_config.sh && tegola serve --config /src/config.toml"
    volumes:
      - ".:/src"
  db:
    image: kartoza/postgis:9.6-2.4
    environment:
      POSTGRES_DBNAME: osm
      POSTGRES_USER: osm
      POSTGRES_PASS: osm
      ALLOW_IP_RANGE: 172.17.0.0/8
    volumes:
      - ".:/src"
      - "/var/lib/postgresql"

  web:
    image: node:alpine
    ports: ["80:8000"]
    links: ["tegola"]
    environment:
      PUBLIC_PATH: "/var/www"
      TILES_URL: "http://tegola:8082/all/{z}/{x}/{y}.pbf"
    working_dir: "/srv/proxy"
    volumes:
      - "./demo:/var/www"
      - "./proxy:/srv/proxy"
    command: ["/srv/proxy/server.sh"]

  maputnik:
    image: maputnik/editor:latest
    ports: ["8888:8888"]

