name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: echo '${{ secrets.DOCKERHUB_PWD }}' | docker login --username xor22h --password-stdin
    - name: Build custom Tegola image
      run: docker build . --file Dockerfile.tegola --tag xor22h/tegola:v0.10.2
    - name: Push Tegola image
      run: docker push xor22h/tegola:v0.10.2
